Crawler mppi
dadosjusbr/coletor-mppi pull request #1
Opened 2021-04-13 15:19 UTC by samarasss

2021-04-13 17:50 UTC, danielfireman requested changes

2021-04-13 17:50 UTC, danielfireman commented on src/utils.py
> +def convert_month(month):
Pacotes/arquivos `utils` não são uma prática tão boa (ao menos não assim, com o coletor nascendo). De toda forma, não precisamos dele. Basta deixar no mesmo arquivo crawler.

2021-04-13 17:50 UTC, danielfireman commented on src/main.py
> +    main()
Pode mover o conteúdo da função para cá, por favor?

2021-04-13 17:50 UTC, danielfireman commented on Readme.md
> +        Ex: Link para download da planilha de remuneração mensal de julho de 2020 - https://www.mppi.mp.br/internet/wp-content/uploads/2020/09/Remuneracao-de-todos-os-membros-ativos-%E2%80%93-julho-2
Pode coloar outros exemplos para deixar super claro as diferenças, por favor?

2021-04-14 11:30 UTC, samarasss commented on src/main.py
> +    main()
De qual função?

2021-04-14 12:06 UTC, danielfireman commented on src/main.py
> +    main()
`main()`

2021-04-14 12:07 UTC, danielfireman approved these changes

2021-04-14 12:07 UTC, danielfireman approved these changes
Note que ainda tem um comentário a ser resolvido antes do merge.

2021-04-14 12:29 UTC, samarasss commented on src/main.py
> +    main()
@danielfireman

2021-04-14 13:27 UTC, merged